### ISSUE TITLE
Captive portal toggol for DOS 19.1

### ISSUE THREAD

**Issue by Mehsud111** [MSe1969/android_packages_overlays_CaptivePortal204#1]
Dear Markus! Thank you for your contribution to the open community. DOS 19.1 built is facing lack of captive portal toggol. Can you please contribute your work to implement this toggol. 

Regards
Mehsud

**Comment by MSe1969** [comment]
My code and build configs are publicly visible, so each Custom ROM project may or may not decide to cherry-pick from available sources.
